// importin mongoose
const mongoose = require("mongoose");
// import bcrypt
// const bcrypt=require('bcrypt')

// now defining the candidate schema
const candidateSchema = new mongoose.Schema({
  name: {
    type: String,
    required: true,
  },
  party:{
     type:String,
     required:true
  },
  age: {
    type: Number,
    required: true,
  },
  votes:[
    {
        user:{
            //here the id(unique id or _id) is generated by mongoose while creating the user 
            type:mongoose.Schema.Types.ObjectId,
            required:true,
            ref:'user'
        },
        votedAt:{
            type:Date  ,
            default:Date.now()
        }
    }
  ] ,
  voteCount:{
    type:Number,
    default:0
  }
 
});

// our schema is ready, now to want to define model to crud operations
const candidate = mongoose.model("candidate", candidateSchema);
module.exports = candidate;
